name: appnation_sc
description: "AppDog"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

# Flutter SDK and Material Design
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

# State Management
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

# Networking
  dio: ^5.4.1

# File and Asset Management
  path_provider: ^2.1.2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: assets/fonts/GalanoGrotesque-Medium.ttf
          weight: 400
        - asset: assets/fonts/GalanoGrotesque-SemiBold.ttf
          weight: 900

# Launcher Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
